name: Mediacom
version: 1.0.0
main:  me.ansandr.mediacom.platforms.spigot.SpigotMain
api-version: 1.13
authors: [ Ansandr ]
description: Add commands to send to player link on social media's
commands:
  media:
permissions:
  mediacom.admin:
    default: op