media:
  discord:
    link: https://discord.com/invite/Yap846T
    message:
      - '{"text": "","extra":[{"text":"Click here to join our ","color":"green"},{"text":"Discord","bold":true,"color":"#5865F2"},{"text":" server!","color":"green"}],"clickEvent":{"action":"open_url","value":"{url}"},"hoverEvent":{"action":"show_text","contents":[{"text":"Click to go to ","color":"green"},{"text":"Discord","bold":true,"color":"#5865F2"},{"text":"!","color":"green"}]}}'
  twitter:
    link: https://twitter.com/yourpage
    message:
      - '{"text": "","extra":[{"text":"Click here to go to our ","color":"green"},{"text":"Twitter","bold":true,"color":"#1DA1F2"},{"text":"!","color":"green"}],"clickEvent":{"action":"open_url","value":"{url}"},"hoverEvent":{"action":"show_text","contents":[{"text":"Click to go to ","color":"green"},{"text":"Twitter","bold":true,"color":"#1DA1F2"},{"text":"!","color":"green"}]}}'
  vk:
    link: https://vk.com/serversocialcraft
    message:
      - '{"text": "","extra":[{"text":"Click here to go to our ","color":"green"},{"text":"VK","bold":true,"color":"#2787F5"},{"text":"!","color":"green"}],"clickEvent":{"action":"open_url","value":"{url}"},"hoverEvent":{"action":"show_text","contents":[{"text":"Click to go to ","color":"green"},{"text":"VK","bold":true,"color":"#2787F5"},{"text":"!","color":"green"}]}}'
  forum:
    link: https://socialcraft.cf
    message:
      - '{"text": "","extra": [{"text":"Click here to go to our ","color":"green"},{"text":"Forums","bold":true,"color":"aqua"},{"text":"!","color":"green"}],"clickEvent":{"action":"open_url","value":"{url}"},"hoverEvent":{"action":"show_text","contents":[{"text":"Click to go to ur ","color":"green"},{"text":"Forums","bold":true,"color":"aqua"},{"text":"!","color":"green"}]}}'
  youtube:
    link: https://www.youtube.com/channel/UC7oFPF2zT_0dG9cgQMksViQ
    message:
      - '{"text": "","extra": [{"text":"Click here to check out our ","color":"green"},{"text":"YouTube","bold":true,"color":"#FF0000"},{"text":" channel!","color":"green"}],"clickEvent":{"action":"open_url","value":"{url}"},"hoverEvent":{"action":"show_text","contents":[{"text":"Click to go to  ","color":"green"},{"text":"YouTube","bold":true,"color":"#FF0000"},{"text":"!","color":"green"}]}}'
  store:
    aliases: [ donate ]
    link: https://donate.socialcraft.cf
    message:
      - '{"text": "","extra": [{"text":"Click here to visit our ","color":"green"},{"text":"Store","bold":true,"color":"light_purple"},{"text":"!","color":"green"}],"clickEvent":{"action":"open_url","value":"{url}"},"hoverEvent":{"action":"show_text","contents":[{"text":"Click to visit our ","color":"green"},{"text":"Store","bold":true,"color":"light_purple"},{"text":"!","color":"green"}]}}'
list:
  - '{"text":"Visit our in social medias!","color":"green"}'
  - '[{"text":"Web: ","color":"yellow"},{"text":"socialcraft.cf","color":"aqua","clickEvent":{"action":"open_url","value":"https://socialcraft.cf"}}]'
  - '[{"text":"VK: ","color":"yellow"},{"text":"vk.com/serversocialcraft","color":"aqua","clickEvent":{"action":"open_url","value":"https://vk.com/serversocialcraft"}}]'
  - '[{"text":"Discord: ","color":"yellow"},{"text":"socialcraft.cf/discord","color":"aqua","clickEvent":{"action":"open_url","value":"https://socialcraft.cf/discord"}}]'
